stages:
- name: Publish image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile.prod
      buildContext: .
      tag: smi-front:latest
      pushRemote: true
      registry: registry.lappis.rocks

- name: Deploy Staging
  when:
    branch: development
  steps:
  - applyYamlConfig:
      path: ./deploy/staging/deployment-front.yaml

- name: Deploy Production
  when:
    branch: master
  steps:
  - applyYamlConfig:
      path: ./deploy/production/deployment-front.yaml


branch:
  include: [ master, development ]
notification: {}
